name             'jenkins_wrapper'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures jenkins_wrapper'
long_description 'Installs/Configures jenkins_wrapper'
version          '0.1.0'

depends 'apt'
depends 'runit'
depends 'jenkins'
depends 'nginx'
depends 'git'
